### ISSUE TITLE
Vulkan load 3D model example?

### ISSUE THREAD

**Issue by tree786isback** [Lyatus/L#1]
Hey,

Been meaning to check this framework out for a while. Was wondering where I can look for any examples which demonstrate loading a 3D mesh (perhaps from an `.obj` file) from disk and rendering using vulkan? Quite stuck on how to achieve this atm.

Cheers

**Comment by tree786isback** [comment]
I'm also on linux, is this framework currently supported for it?

**Comment by tree786isback** [comment]
Ah no worries, I noticed there is a `main.cpp` which seems to have everything I want

**Comment by tree786isback** [comment]
@Lyatus Is the `Issues` section the best place to ask questions? Or is there somewhere better dedicated to Q&A?

**Comment by Lyatus** [comment]
Oh I'm sorry for some reason I didn't see the notifications for this until your last comment. Were you able to do what you want? This engine may not be the best resource if you're looking for a straight example of loading a mesh and then rendering it via Vulkan since those things are accomplished in different modules and all (most likely the `assimp` module but also the `wavefront_obj` module, and then the `vulkan module`). The `Issues` section is definitely the best place to ask questions, provided I read the notifications I'm supposed to 😅

**Comment by tree786isback** [comment]
Hey no worries, thanks for replying!

>  Were you able to do what you want? 

Yeah kinda, I'm trying to figure out how to achieve it by directly writing it in c++ (using the frameworks API). But as I understand in the demo it's currently achieved by using the custom scripting language designed for L?
